[workspace]
members = [
    "blur",
    "canny",
    "cartoonify",
    "desaturate",
    "dramatic",
    "exif",
    "exif-thumbnail",
    "photon-filters",
    "resize",
    "rotate",
    "sepia",
    "sharpen",
]
